### ISSUE TITLE
Not Working Library and Demo

### ISSUE THREAD

**Issue by pratikbutani** [iPaulPro/aFileChooser#57]
I have downloaded Library and just executing Demo, but I am stuck with this problem.

`11-06 09:48:15.589: E/AndroidRuntime(15228): FATAL EXCEPTION: main
11-06 09:48:15.589: E/AndroidRuntime(15228): Process: com.android.documentsui, PID: 15228
11-06 09:48:15.589: E/AndroidRuntime(15228): java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x1000000 cmp=com.desarrollodroide.repos/com.ipaulpro.afilechooser.FileChooserActivity } from ProcessRecord{41ee8330 15228:com.android.documentsui/u0a74} (pid=15228, uid=10074) not exported from uid 10221
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.os.Parcel.readException(Parcel.java:1465)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.os.Parcel.readException(Parcel.java:1419)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2096)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.app.Activity.startActivityForResult(Activity.java:3424)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.app.Activity.startActivityForResult(Activity.java:3385)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at com.android.documentsui.DocumentsActivity.onAppPicked(DocumentsActivity.java:926)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at com.android.documentsui.RootsFragment$2.onItemClick(RootsFragment.java:183)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.widget.AdapterView.performItemClick(AdapterView.java:299)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.widget.AbsListView$3.run(AbsListView.java:3645)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.os.Handler.handleCallback(Handler.java:733)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.os.Looper.loop(Looper.java:136)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at android.app.ActivityThread.main(ActivityThread.java:5001)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at java.lang.reflect.Method.invokeNative(Native Method)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at java.lang.reflect.Method.invoke(Method.java:515)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
11-06 09:48:15.589: E/AndroidRuntime(15228):    at dalvik.system.NativeStart.main(Native Method)`

**Comment by pratikbutani** [comment]
I found solution after long time.

In my tablet i have installed **Library for Developers** which is also use this library as demo but they have not updated yet this code for KitKat so i got error while I choose from Chooser Dialog.

Finally i have uninstalled that application and its working fine now.

Keep Choosing.
